//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CEMM.Web.unitwork {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblworkid;
	protected global::System.Web.UI.WebControls.Label lblworkname;
	protected global::System.Web.UI.WebControls.Label lbllotid;
	protected global::System.Web.UI.WebControls.Label lblworkstartdate;
	protected global::System.Web.UI.WebControls.Label lblworkenddate;


       
    }
}
