//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CEMM.Web.quotaData {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtsrid;
		protected global::System.Web.UI.WebControls.TextBox txtsubitermid;
		protected global::System.Web.UI.WebControls.TextBox txtsubitermsrid;
		protected global::System.Web.UI.WebControls.TextBox txtsubitermname;
		protected global::System.Web.UI.WebControls.TextBox txttoolid;
		protected global::System.Web.UI.WebControls.TextBox txttoolquant;
		protected global::System.Web.UI.WebControls.TextBox txtjcjs;
		protected global::System.Web.UI.WebControls.TextBox txtzljs;
		protected global::System.Web.UI.WebControls.TextBox txtdygx;
		protected global::System.Web.UI.WebControls.TextBox txtisuse;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
