//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CEMM.Web.lot {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lbllotid;
		protected global::System.Web.UI.WebControls.TextBox txtlotname;
		protected global::System.Web.UI.WebControls.TextBox txtlotstartpos;
		protected global::System.Web.UI.WebControls.TextBox txtlotendpos;
		protected global::System.Web.UI.WebControls.TextBox txtprojectid;
		protected global::System.Web.UI.WebControls.TextBox txtConstruparty;
		protected global::System.Web.UI.WebControls.TextBox txtlotstartdate;
		protected global::System.Web.UI.WebControls.TextBox txtlotenddate;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
