//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CEMM.Web.materialCEFactor {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblmfid;
	protected global::System.Web.UI.WebControls.Label lblname;
	protected global::System.Web.UI.WebControls.Label lblcode;
	protected global::System.Web.UI.WebControls.Label lblspecific;
	protected global::System.Web.UI.WebControls.Label lblunit;
	protected global::System.Web.UI.WebControls.Label lblunitmass;
	protected global::System.Web.UI.WebControls.Label lblemissfactor;
	protected global::System.Web.UI.WebControls.Label lblstandardid;


       
    }
}
