//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CEMM.Web.computeResultInfo {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblresultid;
		protected global::System.Web.UI.WebControls.TextBox txtcode;
		protected global::System.Web.UI.WebControls.TextBox txtformName;
		protected global::System.Web.UI.WebControls.TextBox txtunit;
		protected global::System.Web.UI.WebControls.TextBox txtprice;
		protected global::System.Web.UI.WebControls.TextBox txtemissionfactor;
		protected global::System.Web.UI.WebControls.TextBox txttotal_quantity;
		protected global::System.Web.UI.WebControls.TextBox txttotal_emission;
		protected global::System.Web.UI.WebControls.TextBox txttemp_project;
		protected global::System.Web.UI.WebControls.TextBox txttemp_emission;
		protected global::System.Web.UI.WebControls.TextBox txtsubgrade_project;
		protected global::System.Web.UI.WebControls.TextBox txtsubgrade_emission;
		protected global::System.Web.UI.WebControls.TextBox txtpavement_project;
		protected global::System.Web.UI.WebControls.TextBox txtpavement_emission;
		protected global::System.Web.UI.WebControls.TextBox txtbridge_project;
		protected global::System.Web.UI.WebControls.TextBox txtbridge_emission;
		protected global::System.Web.UI.WebControls.TextBox txttunnel_project;
		protected global::System.Web.UI.WebControls.TextBox txttunnel_emission;
		protected global::System.Web.UI.WebControls.TextBox txtcrossing_project;
		protected global::System.Web.UI.WebControls.TextBox txtcrossing_emission;
		protected global::System.Web.UI.WebControls.TextBox txttraffic_project;
		protected global::System.Web.UI.WebControls.TextBox txttraffic_emission;
		protected global::System.Web.UI.WebControls.TextBox txtgreening_project;
		protected global::System.Web.UI.WebControls.TextBox txtgreening_emission;
		protected global::System.Web.UI.WebControls.TextBox txtother_project;
		protected global::System.Web.UI.WebControls.TextBox txtother_emission;
		protected global::System.Web.UI.WebControls.TextBox txtassistant_project;
		protected global::System.Web.UI.WebControls.TextBox txtassistant_emission;
		protected global::System.Web.UI.WebControls.TextBox txttableID;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
