//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CEMM.Web.computeResultInfo {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblresultid;
	protected global::System.Web.UI.WebControls.Label lblcode;
	protected global::System.Web.UI.WebControls.Label lblformName;
	protected global::System.Web.UI.WebControls.Label lblunit;
	protected global::System.Web.UI.WebControls.Label lblprice;
	protected global::System.Web.UI.WebControls.Label lblemissionfactor;
	protected global::System.Web.UI.WebControls.Label lbltotal_quantity;
	protected global::System.Web.UI.WebControls.Label lbltotal_emission;
	protected global::System.Web.UI.WebControls.Label lbltemp_project;
	protected global::System.Web.UI.WebControls.Label lbltemp_emission;
	protected global::System.Web.UI.WebControls.Label lblsubgrade_project;
	protected global::System.Web.UI.WebControls.Label lblsubgrade_emission;
	protected global::System.Web.UI.WebControls.Label lblpavement_project;
	protected global::System.Web.UI.WebControls.Label lblpavement_emission;
	protected global::System.Web.UI.WebControls.Label lblbridge_project;
	protected global::System.Web.UI.WebControls.Label lblbridge_emission;
	protected global::System.Web.UI.WebControls.Label lbltunnel_project;
	protected global::System.Web.UI.WebControls.Label lbltunnel_emission;
	protected global::System.Web.UI.WebControls.Label lblcrossing_project;
	protected global::System.Web.UI.WebControls.Label lblcrossing_emission;
	protected global::System.Web.UI.WebControls.Label lbltraffic_project;
	protected global::System.Web.UI.WebControls.Label lbltraffic_emission;
	protected global::System.Web.UI.WebControls.Label lblgreening_project;
	protected global::System.Web.UI.WebControls.Label lblgreening_emission;
	protected global::System.Web.UI.WebControls.Label lblother_project;
	protected global::System.Web.UI.WebControls.Label lblother_emission;
	protected global::System.Web.UI.WebControls.Label lblassistant_project;
	protected global::System.Web.UI.WebControls.Label lblassistant_emission;
	protected global::System.Web.UI.WebControls.Label lbltableID;


       
    }
}
